/* TUS FOTOS. Lo maneja el etiquetador (tagger). */

const BATCHES = [
  {
    title: "Tanda sin título",
    date: "2026-06-06",
    photos: [
      { src: "images/1-dsc05159-3.jpg", alt: "", tags: ["naturaleza"] },
      { src: "images/2-dsc05169-3.jpg", alt: "", tags: ["naturaleza"] },
      { src: "images/3-dsc05189-3.jpg", alt: "", tags: ["naturaleza"] },
      { src: "images/4-dsc05142-3.jpg", alt: "", tags: ["naturaleza"] },
      { src: "images/5-dsc05193-3.jpg", alt: "", tags: ["naturaleza"] },
      { src: "images/6-dsc05190-3.jpg", alt: "", tags: ["naturaleza"] },
      { src: "images/7-dsc05232-3.jpg", alt: "", tags: ["naturaleza", "retrato"] },
      { src: "images/8-dsc05195-3.jpg", alt: "", tags: ["naturaleza", "retrato"] },
      { src: "images/9-dsc05166-3.jpg", alt: "", tags: ["retrato"] },
      { src: "images/10-dsc05191-3.jpg", alt: "", tags: ["naturaleza"] },
      { src: "images/11-dsc05194-3.jpg", alt: "", tags: ["naturaleza"] },
      { src: "images/12-dsc05156-3.jpg", alt: "", tags: ["naturaleza"] },
      { src: "images/13-dsc05151-3.jpg", alt: "", tags: ["naturaleza", "retrato"] },
      { src: "images/14-dsc05155-3.jpg", alt: "", tags: ["naturaleza"] },
      { src: "images/15-dsc05154-3.jpg", alt: "", tags: ["naturaleza", "retrato"] },
      { src: "images/16-dsc05143-3.jpg", alt: "", tags: ["naturaleza", "retrato"] },
    ],
  },
  {
    title: "Belgrano campeón y Lupe",
    date: "2026-05-25",
    photos: [
      { src: "images/1-dsc03755.jpg", alt: "", tags: ["Perro"] },
      { src: "images/2-dsc03748.jpg", alt: "", tags: ["Perro", "retrato"] },
      { src: "images/3-dsc03754.jpg", alt: "", tags: ["Perro"] },
      { src: "images/4-dsc03741.jpg", alt: "", tags: ["Perro"] },
      { src: "images/5-dsc03745.jpg", alt: "", tags: ["Perro"] },
      { src: "images/6-dsc03737.jpg", alt: "", tags: ["Perro"] },
      { src: "images/7-dsc03736.jpg", alt: "", tags: ["Perro"] },
      { src: "images/8-dsc03735.jpg", alt: "", tags: ["Perro"] },
      { src: "images/9-dsc03732.jpg", alt: "", tags: ["Perro"] },
      { src: "images/10-dsc03738.jpg", alt: "", tags: ["Perro"] },
      { src: "images/11-dsc03731.jpg", alt: "", tags: ["Perro"] },
    ],
  },
  {
    title: "Siesta y Mandarinas",
    date: "2026-05-27",
    photos: [
      { src: "images/1-dsc03861.jpg", alt: "", tags: ["animales", "Perro"] },
      { src: "images/2-dsc03862.jpg", alt: "", tags: ["animales", "Perro"] },
      { src: "images/3-dsc03865.jpg", alt: "", tags: ["animales", "Perro"] },
      { src: "images/4-dsc03864.jpg", alt: "", tags: ["animales", "Perro"] },
      { src: "images/5-dsc03863.jpg", alt: "", tags: ["animales", "Perro"] },
      { src: "images/6-dsc03853.jpg", alt: "", tags: ["animales", "Perro"] },
      { src: "images/7-dsc03859.jpg", alt: "", tags: ["animales", "Perro"] },
      { src: "images/8-dsc03858.jpg", alt: "", tags: ["animales", "Perro"] },
      { src: "images/9-dsc03854.jpg", alt: "", tags: ["animales", "Perro", "retrato"] },
      { src: "images/10-dsc03856.jpg", alt: "", tags: ["animales", "Perro", "retrato"] },
      { src: "images/11-dsc03849.jpg", alt: "", tags: ["animales", "Perro"] },
      { src: "images/12-dsc03850.jpg", alt: "", tags: ["animales", "Perro"] },
      { src: "images/13-dsc03852.jpg", alt: "", tags: ["animales", "Perro"] },
      { src: "images/14-dsc03847.jpg", alt: "", tags: ["animales", "Perro"] },
      { src: "images/15-dsc03846.jpg", alt: "", tags: ["animales", "Perro"] },
      { src: "images/16-dsc03832.jpg", alt: "", tags: ["animales", "Perro"] },
      { src: "images/17-dsc03845.jpg", alt: "", tags: ["animales", "Perro"] },
      { src: "images/18-dsc03843.jpg", alt: "", tags: ["animales", "Perro"] },
      { src: "images/19-dsc03839.jpg", alt: "", tags: ["animales", "Perro"] },
      { src: "images/20-dsc03844.jpg", alt: "", tags: ["animales", "Perro"] },
      { src: "images/21-dsc03835.jpg", alt: "", tags: ["animales", "Perro"] },
      { src: "images/22-dsc03828.jpg", alt: "", tags: ["animales", "Perro"] },
      { src: "images/23-dsc03830.jpg", alt: "", tags: ["animales", "Perro"] },
      { src: "images/24-dsc03838.jpg", alt: "", tags: ["animales", "Perro"] },
      { src: "images/25-dsc03831.jpg", alt: "", tags: ["animales", "Perro"] },
      { src: "images/26-dsc03827.jpg", alt: "", tags: ["animales", "Perro"] },
    ],
  },
  {
    title: "Marcha Ni Una Menos",
    date: "2026-06-03",
    photos: [
      { src: "images/1-dsc04627.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/2-dsc04967.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/3-dsc04937.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/4-dsc04781.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/5-dsc04784.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/6-dsc04999.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/8-dsc04649.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/9-dsc04621.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/10-dsc04987.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/11-dsc04646.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/12-dsc04615.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/13-dsc04659.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/14-dsc04991.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/15-dsc04670.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/16-dsc04697.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/17-dsc04785.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/18-dsc04992.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/19-dsc04990.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/20-dsc04801.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/21-dsc04677.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/22-dsc04689.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/23-dsc04742.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/24-dsc04969.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/25-dsc04783.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/26-dsc04763.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/27-dsc04601.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/28-dsc04612.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/29-dsc04634.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/30-dsc04681.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/31-dsc04719.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/32-dsc04714.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/33-dsc04897.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/34-dsc04797.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/35-dsc04813.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/36-dsc04702.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/37-dsc04766.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/38-dsc04643.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/39-dsc04626.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/40-dsc04888.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/41-dsc04746.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/42-dsc04943.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/43-dsc04942.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/44-dsc04716.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/45-dsc04661.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/46-dsc04651.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/47-dsc04630.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/48-dsc04772.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/49-dsc04743.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/50-dsc04740.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/51-dsc04749.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/52-dsc04684.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/53-dsc04806.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/54-dsc04711.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/55-dsc05013.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/56-dsc04730.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/57-dsc04792.jpg", alt: "", tags: ["Marcha"] },
      { src: "images/59-dsc05007.jpg", alt: "", tags: ["Marcha"] },
    ],
  },
  {
    title: "Brunch en Café Salvaje",
    date: "2026-05-27",
    photos: [
      { src: "images/1-dsc03880-2.jpg", alt: "", tags: ["Cafeteria", "Producto"] },
      { src: "images/2-dsc03873-2.jpg", alt: "", tags: ["Cafeteria", "Producto"] },
      { src: "images/3-dsc03874-2.jpg", alt: "", tags: ["Cafeteria", "Producto"] },
      { src: "images/4-dsc03872-2.jpg", alt: "", tags: ["Cafeteria", "Producto"] },
      { src: "images/5-dsc03867-2.jpg", alt: "", tags: ["Cafeteria", "Producto"] },
      { src: "images/6-dsc03878-2.jpg", alt: "", tags: ["Cafeteria", "Producto"] },
      { src: "images/7-dsc03866-2.jpg", alt: "", tags: ["Cafeteria"] },
    ],
  },
];
